- name: start nginx
  service: name=nginx state=started

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart nginx
  service: name=nginx state=restarted

- name: start uwsgi
  shell: start uwsgi-emperor || true

- name: reload uwsgi
  command: reload uwsgi-emperor

- name: restart uwsgi
  service: name="uwsgi-emperor" state=restarted
